#!/usr/bin/env bun
/*
 * Structural color-token generator.
 *
 * Emits two files that are pure, mechanical expansions of the family × tone
 * grid — hand-maintaining them invites drift and copy/paste bugs:
 *
 *   colors/palette.css            — the `@theme inline` bridge that exposes every
 *                                   ramp tone to Tailwind as `--color-{family}-{tone}`.
 *   foundations/color-utilities.css — the `{family}` / `inverse-{family}` /
 *                                   `{family}-container` utility set, plus the
 *                                   bespoke surface utilities.
 *
 * Run after changing FAMILIES or TONES (defined in ./lib/ramp):
 *   bun run scripts/generate-tokens.ts
 */
import { writeFile } from 'node:fs/promises';
import { TONES, FAMILIES, ACCENT_FAMILIES, label } from './lib/ramp';

// ---------- palette.css ----------

function emitPalette(): string {
	const lines: string[] = [];
	lines.push('/* Palette Color Mappings — GENERATED by scripts/generate-tokens.ts */');
	lines.push('@theme inline {');
	FAMILIES.forEach((family, i) => {
		if (i > 0) lines.push('');
		lines.push(`\t/* ${label(family)} */`);
		for (const tone of TONES) {
			lines.push(`\t--color-${family}-${tone}: var(--theme-color-${family}-${tone});`);
		}
	});
	lines.push('}');
	lines.push('');
	return lines.join('\n');
}

// ---------- color-utilities.css ----------

/** The four utilities every accent family shares. */
function emitFamilyUtilities(f: string): string {
	return [
		`/* ${label(f)} Utility Classes */`,
		`@utility ${f} {`,
		`\t@apply bg-${f} text-on-${f} selection:bg-${f}-container/75! selection:text-on-${f}-container!;`,
		`}`,
		`@utility inverse-${f} {`,
		`\t@apply bg-on-${f} text-${f} selection:bg-on-${f}-container/75! selection:text-${f}-container!;`,
		`}`,
		`@utility ${f}-container {`,
		`\t@apply bg-${f}-container text-on-${f}-container selection:bg-${f}/75! selection:text-on-${f}!;`,
		`}`,
		`@utility inverse-${f}-container {`,
		`\t@apply bg-on-${f}-container text-${f}-container selection:bg-on-${f}/75! selection:text-${f}!;`,
		`}`
	].join('\n');
}

// Surface utilities are irregular (no `!` on most selection colors, extra
// container tiers) so they're authored literally rather than generated.
const SURFACE_UTILITIES = `/* Surface Utility Classes */
@utility surface-dim {
	@apply bg-surface-dim text-on-surface selection:bg-on-surface-variant/75 selection:text-surface;
}
@utility surface {
	@apply bg-surface text-on-surface selection:bg-on-surface-variant/75 selection:text-surface;
}
@utility surface-bright {
	@apply bg-surface-bright text-on-surface selection:bg-on-surface-variant/75 selection:text-surface;
}
@utility inverse-surface {
	@apply bg-on-surface text-surface selection:bg-surface/75! selection:text-on-surface!;
}
@utility inverse-surface-variant {
	@apply bg-on-surface-variant text-surface selection:bg-surface/75! selection:text-on-surface!;
}
@utility surface-container-lowest {
	@apply bg-surface-container-lowest text-on-surface selection:bg-on-surface-variant/75 selection:text-surface;
}
@utility surface-container-low {
	@apply bg-surface-container-low text-on-surface selection:bg-on-surface-variant/75 selection:text-surface;
}
@utility surface-container {
	@apply bg-surface-container text-on-surface selection:bg-on-surface-variant/75 selection:text-surface;
}
@utility surface-container-high {
	@apply bg-surface-container-high text-on-surface selection:bg-on-surface-variant/75 selection:text-surface;
}
@utility surface-container-highest {
	@apply bg-surface-container-highest text-on-surface selection:bg-on-surface-variant/75 selection:text-surface;
}`;

function emitUtilities(): string {
	const blocks: string[] = [
		'/* Color Utility Classes — GENERATED by scripts/generate-tokens.ts */'
	];
	for (const f of ACCENT_FAMILIES) blocks.push(emitFamilyUtilities(f));
	blocks.push(SURFACE_UTILITIES);
	return blocks.join('\n') + '\n';
}

// ---------- Entry point ----------

async function main() {
	await writeFile('src/lib/styles/colors/palette.css', emitPalette(), 'utf8');
	console.log('✓ Wrote src/lib/styles/colors/palette.css');

	await writeFile('src/lib/styles/foundations/color-utilities.css', emitUtilities(), 'utf8');
	console.log('✓ Wrote src/lib/styles/foundations/color-utilities.css');
}

await main();
